### ISSUE TITLE
TypeError: respond is not a function 

### ISSUE THREAD

**Issue by BalasubramaniM** [blakehaswell/mongoose-unique-validator#82]
After updating mongoose to version 5.1.13 from 4.4.10, I get the following error.

```
TypeError: respond is not a function
    at /Users/user/Documents/MyWorkings/Projects/my-app/node_modules/mongoose-unique-validator/index.js:132:33
```
When I downgrade back to an old version, my unique validator seems to be working fine. Also in a new version, when I comment the following code, that is when skipping unique validation,

```
UserSchema.plugin(uniqueValidator, { message: "is already taken." });
```
All is working fine. There might be some changes in recent mongoose version I guess. Request to kindly check and revert back.

Thank you.

**Comment by viveleroi** [comment]
Which version of this plugin are you on? Doesn't sound like you're using our latest. I've just run all of our unit tests against mongoose v5.1.5 and they pass fine.

**Comment by BalasubramaniM** [comment]
Sorry for this totally. I was using older version (V1.0.2). This issue has been fixed and working fine. Thank you.
